"""add notes model

Revision ID: a35af5ac8bf5
Revises: 2d2dd0d54afd
Create Date: 2026-05-29 08:37:12.353617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35af5ac8bf5'
down_revision: Union[str, Sequence[str], None] = '2d2dd0d54afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'phone_number')
    # ### end Alembic commands ###
