"""add_missing_lead_columns

Revision ID: b7d070216c32
Revises: 2e1d49fcdf8c
Create Date: 2026-06-03 19:18:17.550593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d070216c32'
down_revision: Union[str, Sequence[str], None] = '2e1d49fcdf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_full_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone_number'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('channel', postgresql.ENUM('WHATSAPP', 'EMAIL', 'INSTAGRAM', 'GOOGLE_ADS', 'OFFLINE', name='leadchannel'), autoincrement=False, nullable=False),
    sa.Column('stage', postgresql.ENUM('AI_ACTIVE', 'HANDOFF', 'ARCHIVE', name='leadstage'), autoincrement=False, nullable=False),
    sa.Column('is_human_locked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('preferred_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('budget_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('test_scores', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('academic_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ml_conversion_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ai_post_mortem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calendar_booking_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('audit_report_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('resolution_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pkey'))
    )
    op.create_index(op.f('ix_leads_phone_number'), 'leads', ['phone_number'], unique=True)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_full_name'), 'leads', ['full_name'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('messages_lead_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###
