"""Convert programs.id from UUID to INTEGER SERIAL.

Revision ID: vv2w3xprogserial
Revises: uu1v2wmajorkey
Create Date: 2026-08-21 22:50:00.000000

Tables are empty (or FK cols nullable/NULL) so conversion is destructive-safe:
drop FKs → alter PK/FK columns → recreate FKs.
Does not touch temp_universities_clone / temp_programs_clone.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "vv2w3xprogserial"
down_revision: Union[str, Sequence[str], None] = "uu1v2wmajorkey"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (table, column, constraint_name, ondelete or None, nullable)
_FK_SPECS: list[tuple[str, str, str, str | None, bool]] = [
    (
        "education_courses",
        "program_id",
        "education_courses_program_id_fkey",
        None,
        True,
    ),
    (
        "education_majors",
        "program_id",
        "fk_education_majors_program_id",
        None,
        True,
    ),
    (
        "flowx_enrollments",
        "qualification_program_id",
        "flowx_enrollments_qualification_program_id_fkey",
        "SET NULL",
        True,
    ),
    (
        "program_education_major_mappings",
        "program_id",
        "program_education_major_mappings_program_id_fkey",
        "CASCADE",
        False,
    ),
    (
        "program_intake_assignments",
        "program_id",
        "program_intake_assignments_program_id_fkey",
        "CASCADE",
        False,
    ),
    (
        "target_courses",
        "qualification_program_id",
        "fk_target_courses_qualification_program_id",
        None,
        True,
    ),
    (
        "target_programs",
        "program_id",
        "fk_target_programs_program_id",
        None,
        False,
    ),
]


def _fk_names(inspector: sa.Inspector, table: str) -> set[str]:
    if table not in inspector.get_table_names():
        return set()
    return {fk["name"] for fk in inspector.get_foreign_keys(table) if fk.get("name")}


def _drop_fk_if_exists(inspector: sa.Inspector, table: str, name: str) -> None:
    if name in _fk_names(inspector, table):
        op.drop_constraint(name, table, type_="foreignkey")


def _column_type(inspector: sa.Inspector, table: str, column: str) -> str | None:
    if table not in inspector.get_table_names():
        return None
    for col in inspector.get_columns(table):
        if col["name"] == column:
            return str(col["type"]).lower()
    return None


def _alter_uuid_to_integer(
    table: str, column: str, *, nullable: bool
) -> None:
    """Rewrite UUID column as INTEGER. Safe for empty tables / all-NULL values."""
    # Drop/re-add avoids uuid→integer cast failures when any non-null UUID remains.
    op.execute(sa.text(f"ALTER TABLE {table} DROP COLUMN IF EXISTS {column}"))
    op.add_column(
        table,
        sa.Column(column, sa.Integer(), nullable=nullable),
    )


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "programs" not in inspector.get_table_names():
        return

    # 1) Drop FKs pointing at programs.id
    for table, _col, constraint, _ondelete, _nullable in _FK_SPECS:
        _drop_fk_if_exists(inspector, table, constraint)
    inspector = sa.inspect(bind)

    # 2) Convert dependent columns first (programs.id still UUID PK during drop)
    for table, column, _constraint, _ondelete, nullable in _FK_SPECS:
        ctype = _column_type(inspector, table, column)
        if ctype is None:
            continue
        if "uuid" in ctype or "char" in ctype:
            _alter_uuid_to_integer(table, column, nullable=nullable)
        elif "int" not in ctype:
            _alter_uuid_to_integer(table, column, nullable=nullable)

    # 3) Replace programs.id with SERIAL (IDENTITY)
    id_type = _column_type(inspector, "programs", "id") or ""
    if "uuid" in id_type or "char" in id_type:
        # Drop PK + id, add identity integer PK
        pk = inspector.get_pk_constraint("programs")
        pk_name = pk.get("name") if pk else None
        if pk_name:
            op.drop_constraint(pk_name, "programs", type_="primary")
        # Drop uuid default if present
        op.execute(sa.text("ALTER TABLE programs ALTER COLUMN id DROP DEFAULT"))
        op.execute(sa.text("ALTER TABLE programs DROP COLUMN id"))
        op.execute(
            sa.text(
                "ALTER TABLE programs ADD COLUMN id INTEGER "
                "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            )
        )
        # Ensure sequence starts at 1 (identity already does on empty table)
        op.execute(sa.text("ALTER TABLE programs ALTER COLUMN id RESTART WITH 1"))
    elif "int" not in id_type:
        raise RuntimeError(f"Unexpected programs.id type: {id_type}")

    # Recreate index commonly present on programs.id (PK already indexes)
    inspector = sa.inspect(bind)
    existing_indexes = {ix["name"] for ix in inspector.get_indexes("programs")}
    if "ix_programs_id" not in existing_indexes:
        # SQLAlchemy model uses index=True on PK; optional named index
        pass

    # 4) Recreate FKs
    inspector = sa.inspect(bind)
    for table, column, constraint, ondelete, _nullable in _FK_SPECS:
        if table not in inspector.get_table_names():
            continue
        if _column_type(inspector, table, column) is None:
            continue
        if constraint in _fk_names(inspector, table):
            continue
        op.create_foreign_key(
            constraint,
            table,
            "programs",
            [column],
            ["id"],
            ondelete=ondelete,
        )


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "programs" not in inspector.get_table_names():
        return

    for table, _col, constraint, _ondelete, _nullable in _FK_SPECS:
        _drop_fk_if_exists(inspector, table, constraint)

    for table, column, _constraint, _ondelete, nullable in _FK_SPECS:
        if table not in inspector.get_table_names():
            continue
        if _column_type(inspector, table, column) is None:
            continue
        op.execute(sa.text(f"ALTER TABLE {table} DROP COLUMN IF EXISTS {column}"))
        op.add_column(
            table,
            sa.Column(column, postgresql.UUID(as_uuid=True), nullable=nullable),
        )

    pk = inspector.get_pk_constraint("programs")
    pk_name = pk.get("name") if pk else None
    if pk_name:
        op.drop_constraint(pk_name, "programs", type_="primary")
    op.execute(sa.text("ALTER TABLE programs DROP COLUMN IF EXISTS id"))
    op.add_column(
        "programs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    op.execute(sa.text("ALTER TABLE programs ALTER COLUMN id SET DEFAULT gen_random_uuid()"))
    op.create_primary_key("programs_pkey", "programs", ["id"])

    for table, column, constraint, ondelete, _nullable in _FK_SPECS:
        if table not in inspector.get_table_names():
            continue
        op.create_foreign_key(
            constraint,
            table,
            "programs",
            [column],
            ["id"],
            ondelete=ondelete,
        )
