/**
 * Snapshot restored after accidental Reset to Nexus defaults (Chrome localStorage recovery).
 * Applied once via admin settings persist migrate v7.
 */
import type { FeeCatalog } from './feeCatalogSchema';

export const RECOVERED_FEE_CATALOG: FeeCatalog = {
  "currency": "INR",
  "services": [
    {
      "id": "general-counselling",
      "name": "General Counselling",
      "description": "Initial study-abroad guidance, goals, and pathway overview.",
      "basePriceInr": 5000,
      "active": true,
      "sortOrder": 10,
      "masterProcessKey": "counselling",
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T05:00:01.360Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "university-shortlisting-2",
      "name": "University Shortlisting",
      "description": "Compare destinations, universities, and programs and lock a realistic target shortlist.",
      "basePriceInr": 2000,
      "active": true,
      "sortOrder": 20,
      "masterProcessKey": "college_finding",
      "createdAt": "2026-08-10T05:49:27.481Z",
      "updatedAt": "2026-08-10T06:16:15.743Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "university-shortlisting",
      "name": "Profile Assessment & Building",
      "description": "Match destinations, institutions, and programs to the profile.",
      "basePriceInr": 3000,
      "active": true,
      "sortOrder": 30,
      "masterProcessKey": "college_finding",
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T06:16:15.743Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "documentation",
      "name": "Application Documentation",
      "description": "Collect, review, and organise application documents.",
      "basePriceInr": 4000,
      "active": true,
      "sortOrder": 40,
      "masterProcessKey": "document_submission",
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T05:50:28.571Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "sop-drafting",
      "name": "Statement of Purpose Drafting/ Essay Writing",
      "description": "Draft and refine statement of purpose / essays.",
      "basePriceInr": 4000,
      "active": true,
      "sortOrder": 50,
      "masterProcessKey": "document_submission",
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T05:50:28.571Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "digital-presence-profile-boosting",
      "name": "Digital Presence & Profile Boosting",
      "description": "Strengthen LinkedIn / profile presentation so outreach and applications look credible.",
      "basePriceInr": 8000,
      "active": true,
      "sortOrder": 60,
      "masterProcessKey": "document_submission",
      "createdAt": "2026-08-10T05:52:03.714Z",
      "updatedAt": "2026-08-10T06:16:15.743Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "education-loan-assistance",
      "name": "Education Loan Assistance",
      "description": "Collect, check, and prepare application documents so the file is submission-ready.",
      "basePriceInr": 4000,
      "active": true,
      "sortOrder": 70,
      "masterProcessKey": "document_submission",
      "createdAt": "2026-08-10T05:19:50.093Z",
      "updatedAt": "2026-08-10T06:16:15.743Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "letter-of-recommendation-drafting",
      "name": "Letter of Recommendation Drafting",
      "description": "Collect, check, and prepare application documents so the file is submission-ready.",
      "basePriceInr": 5000,
      "active": true,
      "sortOrder": 80,
      "masterProcessKey": "document_submission",
      "createdAt": "2026-08-10T05:11:20.483Z",
      "updatedAt": "2026-08-10T06:16:15.743Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "aptitude-test-prep-guidance",
      "name": "Aptitude Test Prep Guidance",
      "description": "SAT / GRE / GMAT  prep planning.",
      "basePriceInr": 3000,
      "active": true,
      "sortOrder": 90,
      "masterProcessKey": "tests",
      "createdAt": "2026-08-10T05:14:17.417Z",
      "updatedAt": "2026-08-10T05:52:30.499Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "test-prep-guidance",
      "name": "English Test Prep Guidance",
      "description": "IELTS / TOEFL / PTE / Duolingo prep planning.",
      "basePriceInr": 3000,
      "active": true,
      "sortOrder": 100,
      "masterProcessKey": "tests",
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T05:52:30.499Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "application-review",
      "name": "Application Review",
      "description": "Review application drafts and submission readiness.",
      "basePriceInr": 10000,
      "active": true,
      "sortOrder": 110,
      "masterProcessKey": "admission_processing",
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T05:52:30.499Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "visa-application-help",
      "name": "Visa Application Guidance",
      "description": "Visa forms, evidence checklist, and interview prep.",
      "basePriceInr": 15000,
      "active": true,
      "sortOrder": 120,
      "masterProcessKey": "visa_processing",
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T05:52:30.499Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "interview-prep",
      "name": "Visa Mock Interview",
      "description": "University or visa interview coaching.",
      "basePriceInr": 7000,
      "active": true,
      "sortOrder": 130,
      "masterProcessKey": "visa_processing",
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T05:52:30.499Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "for",
      "name": "Forex & Remittance Guidance",
      "description": "Complete fee, travel, and logistics steps before the student leaves for campus.",
      "basePriceInr": 1000,
      "active": true,
      "sortOrder": 140,
      "masterProcessKey": "predeparture_travel",
      "createdAt": "2026-08-10T05:20:30.110Z",
      "updatedAt": "2026-08-10T06:16:15.743Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "housing-accommodation-guidance",
      "name": "Housing & Accommodation Guidance",
      "description": "Complete fee, travel, and logistics steps before the student leaves for campus.",
      "basePriceInr": 1000,
      "active": true,
      "sortOrder": 150,
      "masterProcessKey": "predeparture_travel",
      "createdAt": "2026-08-10T05:21:09.387Z",
      "updatedAt": "2026-08-10T06:16:15.743Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "student-health-campus-insurance",
      "name": "Student Health & Campus Insurance",
      "description": "Complete fee, travel, and logistics steps before the student leaves for campus.",
      "basePriceInr": 1000,
      "active": true,
      "sortOrder": 160,
      "masterProcessKey": "predeparture_travel",
      "createdAt": "2026-08-10T05:18:52.201Z",
      "updatedAt": "2026-08-10T06:16:15.743Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "job-application-help",
      "name": "Job Application Help",
      "description": "Billable counselling service tied to the student journey.",
      "basePriceInr": 0,
      "active": true,
      "sortOrder": 170,
      "masterProcessKey": "other",
      "createdAt": "2026-08-10T06:07:29.768Z",
      "updatedAt": "2026-08-10T06:14:07.675Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "resume-drafting",
      "name": "Resume Drafting",
      "description": "Billable counselling service tied to the student journey.",
      "basePriceInr": 0,
      "active": true,
      "sortOrder": 180,
      "masterProcessKey": "other",
      "createdAt": "2026-08-10T06:13:30.436Z",
      "updatedAt": "2026-08-10T06:14:07.675Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    }
  ],
  "bundles": [
    {
      "id": "essentials",
      "name": "Pathfinder",
      "description": "General Counselling + University Shortlisting + Profile Assessment & Building + Application Documentation + Statement of Purpose Drafting/ Essay Writing",
      "serviceIds": [
        "general-counselling",
        "university-shortlisting",
        "documentation",
        "university-shortlisting-2",
        "sop-drafting"
      ],
      "packagePriceInr": 0,
      "active": true,
      "sortOrder": 10,
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T06:17:19.497Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "end-to-end",
      "name": "Pathfinder Plus",
      "description": "General Counselling + University Shortlisting + Profile Assessment & Building + Application Documentation + Statement of Purpose Drafting/ Essay Writing + Education Loan Assistance + Letter of Recommendation Drafting + Aptitude Test Prep Gu",
      "serviceIds": [
        "general-counselling",
        "university-shortlisting",
        "documentation",
        "sop-drafting",
        "test-prep-guidance",
        "application-review",
        "visa-application-help",
        "interview-prep",
        "education-loan-assistance",
        "letter-of-recommendation-drafting",
        "aptitude-test-prep-guidance",
        "university-shortlisting-2"
      ],
      "packagePriceInr": 0,
      "active": true,
      "sortOrder": 20,
      "createdAt": "2026-08-10T05:00:01.360Z",
      "updatedAt": "2026-08-10T06:17:19.497Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    },
    {
      "id": "elite",
      "name": "Elite",
      "description": "General Counselling + University Shortlisting + Profile Assessment & Building + Application Documentation + Statement of Purpose Drafting/ Essay Writing + Digital Presence & Profile Boosting + Education Loan Assistance + Letter of Recommend",
      "serviceIds": [
        "general-counselling",
        "university-shortlisting-2",
        "university-shortlisting",
        "documentation",
        "sop-drafting",
        "digital-presence-profile-boosting",
        "resume-drafting",
        "visa-application-help",
        "application-review",
        "job-application-help",
        "test-prep-guidance",
        "student-health-campus-insurance",
        "aptitude-test-prep-guidance",
        "housing-accommodation-guidance",
        "letter-of-recommendation-drafting",
        "for",
        "education-loan-assistance",
        "interview-prep"
      ],
      "packagePriceInr": 0,
      "active": true,
      "sortOrder": 30,
      "createdAt": "2026-08-10T06:20:08.284Z",
      "updatedAt": "2026-08-10T06:20:45.403Z",
      "createdBy": "Ishq Ahmed",
      "updatedBy": "Ishq Ahmed"
    }
  ]
} as FeeCatalog;
