import { z } from 'zod';
import { discountTypeSchema, GSTIN_REGEX, isValidGstin } from './billingSettingsSchema';
import { businessTodayIsoDate } from '../utils/timezone';

export const INVOICE_SAC_DEFAULT = '998311';
export const INVOICE_SAC_OPTIONS = [
  { value: '998311', label: '998311 — Management consulting' },
  { value: '999799', label: '999799 — Other education / support services' },
] as const;

export const PAYMENT_TERMS_PRESETS = [
  'Due upon receipt',
  '100% advance before visa filing',
  '50% advance, balance before filing',
] as const;

export const INVOICE_CANCELLATION_REASON_OTHER = 'other' as const;

export const INVOICE_CANCELLATION_REASON_OPTIONS = [
  {
    value: 'client_requested',
    label: 'Client Requested Cancellation (Client changed their mind or withdrew)',
  },
  {
    value: 'duplicate',
    label: 'Duplicate Invoice (Generated by mistake)',
  },
  {
    value: 'incorrect_billing',
    label: 'Incorrect Billing Details (Needs to be reissued with correct info/address)',
  },
  {
    value: 'package_change',
    label: 'Package / Plan Change (Client upgraded or downgraded their service tier)',
  },
  {
    value: 'non_payment_expired',
    label: 'Non-Payment / Expired (Unpaid invoice past its validity window)',
  },
  {
    value: 'services_terminated',
    label: 'Services Terminated / Refunded (Agreement ended or refunded after issuance)',
  },
  { value: INVOICE_CANCELLATION_REASON_OTHER, label: 'Other / Custom Reason' },
] as const;

export type InvoiceCancellationReasonCode =
  (typeof INVOICE_CANCELLATION_REASON_OPTIONS)[number]['value'];

export function resolveInvoiceCancellationReason(
  code: string | null | undefined,
  detail: string | null | undefined
): { ok: true; reason: string } | { ok: false; error: string; focus: 'code' | 'detail' } {
  const normalizedCode = String(code || '').trim();
  const normalizedDetail = String(detail || '').trim();
  const option = INVOICE_CANCELLATION_REASON_OPTIONS.find(
    row => row.value === normalizedCode
  );
  if (!option) {
    return {
      ok: false,
      error: 'Select a cancellation reason.',
      focus: 'code',
    };
  }
  if (option.value === INVOICE_CANCELLATION_REASON_OTHER) {
    if (!normalizedDetail) {
      return {
        ok: false,
        error: 'Enter a custom cancellation reason.',
        focus: 'detail',
      };
    }
    return { ok: true, reason: normalizedDetail };
  }
  return { ok: true, reason: option.label };
}

export function displayInvoiceCancellationReason(
  code: string | null | undefined,
  detail: string | null | undefined
): string {
  const resolved = resolveInvoiceCancellationReason(code, detail);
  if (resolved.ok) return resolved.reason;
  return String(detail || '').trim();
}

export const invoiceStatusSchema = z.enum(['draft', 'issued', 'void', 'archived']);
export type InvoiceStatus = z.infer<typeof invoiceStatusSchema>;

export const billingModeSchema = z.enum(['package', 'alacarte']);
export type InvoiceBillingMode = z.infer<typeof billingModeSchema>;

export const invoiceLineSchema = z.object({
  id: z.string().min(1),
  serviceId: z.string().optional().default(''),
  name: z.string().trim().min(1, 'Service name is required.').max(120),
  quantity: z.coerce.number().min(0.01, 'Quantity must be positive.').max(10_000),
  unitPriceInr: z.coerce.number().min(0).max(10_000_000),
});

export type InvoiceLine = z.infer<typeof invoiceLineSchema>;

const panSchema = z
  .string()
  .trim()
  .transform(v => v.toUpperCase())
  .refine(v => !v || /^[A-Z]{5}[0-9]{4}[A-Z]$/.test(v), 'Enter a valid 10-character PAN.');

const optionalGstinSchema = z
  .string()
  .trim()
  .transform(v => v.toUpperCase())
  .refine(v => !v || isValidGstin(v), 'Enter a valid 15-character GSTIN.');

export const invoiceDocumentSchema = z
  .object({
    id: z.string().min(1),
    status: invoiceStatusSchema,
    invoiceNumber: z.string().nullable(),
    createdAt: z.string(),
    updatedAt: z.string(),
    /** Last explicit “Save draft” (or create) time — not overwritten on issue/cancel. */
    draftSavedAt: z.string().optional().default(''),
    issuedAt: z.string().nullable(),
    voidedAt: z.string().nullable(),

    studentFullName: z.string().trim().max(200).default(''),
    studentMasterId: z.string().trim().max(40).optional().default(''),
    leadId: z.number().int().positive().nullable(),
    phone: z.string().trim().max(40).optional().default(''),
    email: z.string().trim().max(200).default(''),
    addressStreet: z.string().trim().max(300).optional().default(''),
    addressCity: z.string().trim().max(120).optional().default(''),
    addressState: z.string().trim().max(120).optional().default(''),
    addressCountry: z.string().trim().max(2).optional().default(''),
    addressPincode: z.string().trim().max(12).optional().default(''),
    destinationCountries: z
      .array(z.string().trim())
      .transform(values =>
        values
          .map(value => value.toUpperCase())
          .filter(value => value.length === 2)
      )
      .default([]),

    placeOfSupplyStateCode: z
      .string()
      .trim()
      .transform(value => (value.length === 2 ? value : '27')),
    buyerGstin: optionalGstinSchema.optional().default(''),
    pan: panSchema.optional().default(''),
    sacCode: z.string().trim().min(4).max(8),
    forceExempt: z.boolean().default(false),

    billingMode: billingModeSchema,
    packageId: z.string().optional().default(''),
    packageName: z.string().optional().default(''),
    /** Snapshot of package invoice blurb (≤75) shown under the package name. */
    packageInvoiceDescription: z.string().trim().max(75).optional().default(''),
    lines: z.array(invoiceLineSchema).default([]),

    discountType: discountTypeSchema,
    discountValue: z.coerce.number().min(0).max(1_000_000),
    discountReason: z.string().trim().max(60).optional().default(''),
    approvedByStaffId: z.string().trim().max(40).optional().default(''),
    approvedByStaffName: z.string().trim().max(120).optional().default(''),

    paymentTerms: z
      .string()
      .trim()
      .max(200)
      .transform(value => value || PAYMENT_TERMS_PRESETS[0]),
    selectedBankIndex: z.coerce.number().int().min(0).max(19),
    upiVpa: z
      .string()
      .trim()
      .max(100)
      .refine(v => !v || /^[\w.\-]+@[\w.\-]+$/.test(v), 'Enter a valid UPI ID (e.g. nexus@hdfc).'),

    invoiceDate: z.string().min(1),
    dueDate: z.string().min(1),
    counselorId: z.string().trim().max(40).optional().default(''),
    counselorName: z.string().trim().max(120).optional().default(''),
    internalNotes: z.string().trim().max(2000).optional().default(''),
    /** Preset code from INVOICE_CANCELLATION_REASON_OPTIONS; set when cancelling. */
    cancellationReasonCode: z.string().trim().max(40).optional().default(''),
    /** Required when cancellationReasonCode is `other`. */
    cancellationReasonDetail: z.string().trim().max(500).optional().default(''),

    /** Snapshots filled on issue */
    orgGstinSnapshot: z.string().optional().default(''),
    gstPercentageSnapshot: z.number().optional().default(18),
    finalPayableSnapshot: z.number().optional().default(0),
    /** Cloudflare R2 object key after Issue/Cancel uploads the PDF */
    cloudStorageKey: z.string().trim().max(500).optional().default(''),
    /** Last known view/download URL (presigned or signed); refresh via API when opening. */
    cloudDownloadUrl: z.string().trim().max(2000).optional().default(''),
    /** Issued PDF in R2 — kept after cancel so both files stay downloadable. */
    issuedCloudStorageKey: z.string().trim().max(500).optional().default(''),
    issuedCloudDownloadUrl: z.string().trim().max(2000).optional().default(''),
    /** Cancelled PDF in R2. */
    cancelledCloudStorageKey: z.string().trim().max(500).optional().default(''),
    cancelledCloudDownloadUrl: z.string().trim().max(2000).optional().default(''),
  })
  .superRefine((values, ctx) => {
    if (values.discountType === 'percentage' && values.discountValue > 100) {
      ctx.addIssue({
        code: 'custom',
        path: ['discountValue'],
        message: 'Percentage discount cannot exceed 100%.',
      });
    }
    if (values.buyerGstin && !GSTIN_REGEX.test(values.buyerGstin)) {
      ctx.addIssue({
        code: 'custom',
        path: ['buyerGstin'],
        message: 'Enter a valid buyer GSTIN.',
      });
    }
  });

export type InvoiceDocument = z.infer<typeof invoiceDocumentSchema>;

export function createInvoiceLineId(): string {
  return `line_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

export function createInvoiceId(): string {
  return `inv_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
}

function addDaysIso(iso: string, days: number): string {
  const [y, m, d] = iso.split('-').map(Number);
  const dt = new Date(Date.UTC(y, (m || 1) - 1, d || 1));
  dt.setUTCDate(dt.getUTCDate() + days);
  const yy = dt.getUTCFullYear();
  const mm = String(dt.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(dt.getUTCDate()).padStart(2, '0');
  return `${yy}-${mm}-${dd}`;
}

/** Shift a YYYY-MM-DD calendar date by N days (timezone-agnostic). */
export function shiftIsoDate(iso: string, days: number): string {
  return addDaysIso(iso, days);
}

export function createEmptyInvoiceDraft(defaults?: {
  placeOfSupplyStateCode?: string;
  discountType?: 'percentage' | 'fixed';
  discountValue?: number;
  discountReason?: string;
  paymentTerms?: string;
  sacCode?: string;
  /** IANA timezone from Nexus Settings (e.g. Asia/Kolkata). */
  timezone?: string;
  invoiceDate?: string;
}): InvoiceDocument {
  const invoiceDate =
    defaults?.invoiceDate || businessTodayIsoDate(defaults?.timezone || 'UTC');
  const now = new Date().toISOString();
  return {
    id: createInvoiceId(),
    status: 'draft',
    invoiceNumber: null,
    createdAt: now,
    updatedAt: now,
    draftSavedAt: now,
    issuedAt: null,
    voidedAt: null,
    studentFullName: '',
    studentMasterId: '',
    leadId: null,
    phone: '',
    email: '',
    addressStreet: '',
    addressCity: '',
    addressState: '',
    addressCountry: '',
    addressPincode: '',
    destinationCountries: [],
    placeOfSupplyStateCode: defaults?.placeOfSupplyStateCode || '27',
    buyerGstin: '',
    pan: '',
    sacCode: defaults?.sacCode || INVOICE_SAC_DEFAULT,
    forceExempt: false,
    billingMode: 'package',
    packageId: '',
    packageName: '',
    packageInvoiceDescription: '',
    lines: [],
    discountType: defaults?.discountType || 'percentage',
    discountValue: defaults?.discountValue ?? 0,
    discountReason: defaults?.discountReason || '',
    approvedByStaffId: '',
    approvedByStaffName: '',
    paymentTerms: defaults?.paymentTerms || PAYMENT_TERMS_PRESETS[0],
    selectedBankIndex: 0,
    upiVpa: '',
    invoiceDate,
    dueDate: addDaysIso(invoiceDate, 7),
    counselorId: '',
    counselorName: '',
    internalNotes: '',
    cancellationReasonCode: '',
    cancellationReasonDetail: '',
    orgGstinSnapshot: '',
    gstPercentageSnapshot: 18,
    finalPayableSnapshot: 0,
    cloudStorageKey: '',
    cloudDownloadUrl: '',
    issuedCloudStorageKey: '',
    issuedCloudDownloadUrl: '',
    cancelledCloudStorageKey: '',
    cancelledCloudDownloadUrl: '',
  };
}

export function issuedStorageKeyFromCancelled(key: string): string {
  return key.replace(/_Cancelled(\.pdf)?$/i, '_Issued$1');
}

export function resolveIssuedCloudStorageKey(doc: {
  issuedCloudStorageKey?: string;
  cancelledCloudStorageKey?: string;
  cloudStorageKey?: string;
}): string {
  const issued = (doc.issuedCloudStorageKey || '').trim();
  if (issued) return issued;
  const legacy = (doc.cloudStorageKey || '').trim();
  if (/_Cancelled\.pdf$/i.test(legacy)) {
    return issuedStorageKeyFromCancelled(legacy);
  }
  if (legacy) return legacy;
  const cancelled = (doc.cancelledCloudStorageKey || '').trim();
  return cancelled ? issuedStorageKeyFromCancelled(cancelled) : '';
}

export function resolveCancelledCloudStorageKey(doc: {
  cancelledCloudStorageKey?: string;
  cloudStorageKey?: string;
}): string {
  const cancelled = (doc.cancelledCloudStorageKey || '').trim();
  if (cancelled) return cancelled;
  const legacy = (doc.cloudStorageKey || '').trim();
  return /_Cancelled\.pdf$/i.test(legacy) ? legacy : '';
}
